# Default configuration for CCMMF Phase 4 workflows
default:
  flags:
    production: false
  paths:
    ccmmf_dir: "/projectnb2/dietzelab/ccmmf"
    data_dir: "data"
    raw_data_dir: "data_raw"
    cache_dir: "cache"
    pecan_outdir: "/projectnb2/dietzelab/ccmmf/modelout/ccmmf_phase_2b_mixed_pfts_20250701"
  pecan_xml_template: "data_raw/template.xml"
  sites:
    design_points_file: "data_raw/sa_design_points.csv"
  sensitivity:
    sigma_levels: [-2, -1, 1, 2] # for faster runs
  # Or use [-3, -2, -1, 1, 2, 3] Standard
  # ensemble:
  #   size: 20
  #   n_met: 10
  # run:
  #   start_date: "2016-01-01"
  #   end_date: "2023-12-31"
  projection:
    ca_albers_crs: 3310