project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "Sensitivity Analysis"
  description: "Uncertainty and sensitivity analysis of SIPNET ecosystem model"
  repo-url: https://github.com/ccmmf/uncertainty
  repo-actions: [issue, source]
  
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Home"
        contents:
          - text: "Overview"
            href: index.qmd
      - section: "Reports"
        contents:
          - text: "Local Sensitivity"
            href: analysis/local_sensitivity.qmd
          - text: "Global Sensitivity"
            href: analysis/global_sensitivity.qmd
          - text: "Variance Decomposition"
            href: analysis/variance_decomposition.qmd
      - section: "Docs"
        contents:
          - text: "Methodology"
            href: docs/methodology.qmd
          - text: "Technical Documentation"
            href: docs/workflow_documentation.qmd
          - text: "References"
            href: docs/references.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true