#!/usr/bin/env Rscript

# 001_setup_design_points.R
# Prepares design points for the uncertainty analysis pipeline.
#
# Reads the canonical design_points.csv produced by the downscaling
# clustering workflow (020_cluster_and_select_design_points.R).
# In development mode, subsets to n_sample sites for fast iteration.
# In production mode, uses all sites.

library(config)
library(dplyr)
library(readr)
library(PEcAn.logger)

PEcAn.logger::logger.info("Starting 001_setup_design_points.R")

cfg <- config::get(file = "000-config.yml")

production <- isTRUE(cfg$flags$production)

# read the shared design points (written by downscaling/020_cluster_...)
design_points_csv <- cfg$paths$design_points
out_file <- file.path(cfg$paths$raw_data_dir, "sa_design_points.csv")

if (!file.exists(design_points_csv)) {
  PEcAn.logger::logger.severe(
    "Design points not found: ", design_points_csv,
    "\nThese are generated by the downscaling clustering workflow."
  )
}

design_points <- readr::read_csv(design_points_csv, show_col_types = FALSE)

# map LandIQ PFT names to PEcAn PFT names
design_points <- design_points |>
  dplyr::mutate(
    pft = dplyr::case_when(
      pft == "annual crop" ~ "grass",
      pft == "woody perennial crop" ~ "temperate.deciduous",
      TRUE ~ NA_character_
    )
  ) |>
  dplyr::filter(!is.na(pft))

if (production) {
  # production: use all sites
  final_data <- design_points |>
    dplyr::select(site_id, lat, lon, pft)
  PEcAn.logger::logger.info(
    "Production mode: using all ", nrow(final_data), " sites"
  )
} else {
  # development: random subset for fast testing
  n_sample <- cfg$sites$n_sample %||% 10L
  set.seed(42)
  final_data <- design_points |>
    dplyr::slice_sample(n = min(n_sample, nrow(design_points))) |>
    dplyr::select(site_id, lat, lon, pft)
  PEcAn.logger::logger.info(
    "Development mode: sampled ", nrow(final_data), " of ",
    nrow(design_points), " sites"
  )
}

readr::write_csv(final_data, out_file)
PEcAn.logger::logger.info("Wrote SA design points to: ", out_file)