#!/usr/bin/env Rscript

# =======================================================================
# 001_setup_design_points.R
# Prepares design points for Uncertainty Analysis.
#
# Currently, this script consumes the 'design_points.csv' from the shared
# directory. At this stage of the project, these are MANUALLY SELECTED 
# points (198 sites), not yet the output of the automated clustering 
# workflow.
#
# TODO: Once the integration architecture between the Downscaling and 
# Uncertainty repos is finalized, refactor this script, continue to consume 
# the artifact generated by that pipeline.
# =======================================================================

library(config)
library(dplyr)
library(readr)
library(PEcAn.logger)

PEcAn.logger::logger.info("*** Starting 001_setup_design_points.R ***")

cfg <- config::get(file = "000-config.yml")

# Define paths based on config
master_file <-  "/projectnb/dietzelab/abv1/ccmmf/uncertainty_test/data_raw/design_points_198.csv" # cfg$paths$master_design_points
out_file    <- file.path(cfg$paths$raw_data_dir, basename(cfg$sites$design_points_file))

if (!file.exists(master_file)) {
  PEcAn.logger::logger.severe(
    paste0("Could not find master design points at: ", master_file,
           "\nEnsure the shared data is available in the CCMMF data directory.")
  )
}

master_data <- readr::read_csv(master_file, show_col_types = FALSE)

n_sample <- if(!is.null(cfg$sites$n_sample)) cfg$sites$n_sample else 10
set.seed(42) # Ensure reproducibility of the random subset
final_data <- master_data |>
  # Map LandIQ PFT names to PEcAn PFT names (currently used two pft in original design_points.csv)
  # This mapping ensures compatibility whether the input is manual or clustered
  dplyr::mutate(
    pft = dplyr::case_when(
      pft == "annual crop" ~ "grass",
      pft == "woody perennial crop" ~ "temperate.deciduous",
      TRUE ~ NA_character_
    )
  ) |>
  dplyr::filter(!is.na(pft)) |>
  dplyr::slice_sample(n = n_sample) |>
  dplyr::select(site_id, lat, lon, pft)

readr::write_csv(final_data, out_file)

PEcAn.logger::logger.info(paste("Saved processed SA design points to:", out_file))
PEcAn.logger::logger.info("*** Finished 001_setup_design_points.R ***")