#!/usr/bin/env Rscript
# Convert Sobol design matrix to PEcAn sample objects (samples.Rdata).
#
# Reads the design matrix from 021, groups columns by PFT using the
# param_sources metadata, and writes ensemble.samples + trait.samples
# in the format expected by PEcAn's run.write.configs
#
# Management columns (mgmt.*) are skipped - they flow through events.in
# files generated by 023, not through sipnet.param

library(PEcAn.logger)
library(PEcAn.settings, include.only = "read.settings")
library(readr, include.only = c("read_csv", "write_csv"))
library(yaml, include.only = "read_yaml")


opts <- list(
  optparse::make_option(c("-c", "--config"),
    default = "000-config.yml",
    help = "Path to project config YAML [default: %default]"
  ),
  optparse::make_option(c("-d", "--design"),
    default = "data/sobol_design_matrix.csv",
    help = "Path to Sobol design matrix CSV [default: %default]"
  ),
  optparse::make_option(c("-f", "--force"),
    action = "store_true", default = FALSE,
    help = "Overwrite existing output"
  )
)

args <- optparse::parse_args(optparse::OptionParser(option_list = opts))


# config
cfg <- yaml::read_yaml(args$config)
settings <- PEcAn.settings::read.settings(cfg$settings_xml)

samples_outfile <- file.path(settings$outdir, "samples.Rdata")
design_outfile <- "data/input_design.csv"

if (!args$force && file.exists(samples_outfile) && file.exists(design_outfile)) {
  PEcAn.logger::logger.info(
    "Outputs exist: ", samples_outfile, ". Use --force to regenerate. Skipping."
  )
  quit(save = "no", status = 0)
}

if (!dir.exists(settings$outdir)) {
  dir.create(settings$outdir, recursive = TRUE)
}

# load design matrix and metadata from 021
design_path <- args$design
if (!file.exists(design_path)) {
  PEcAn.logger::logger.severe("Design matrix not found: ", design_path)
}

meta_path <- sub("\\.csv$", "_metadata.rds", design_path)
if (!file.exists(meta_path)) {
  PEcAn.logger::logger.severe("Design metadata not found: ", meta_path)
}

sobol_design <- readr::read_csv(design_path, show_col_types = FALSE)
metadata <- readRDS(meta_path)

PEcAn.logger::logger.info(
  "Loaded design: ", nrow(sobol_design), " samples x ", ncol(sobol_design), " columns"
)

# identify active PFTs from site assignments
site_pfts <- metadata$site_pfts
if (is.null(site_pfts) || length(site_pfts) == 0) {
  # fall back to extracting from settings
  site_pfts <- unique(unlist(
    purrr::map(settings$run, \(s) s$site$pft)
  ))
}

if (length(site_pfts) == 0) {
  PEcAn.logger::logger.severe("No PFTs found in metadata or settings")
}

PEcAn.logger::logger.info("Active PFTs: ", paste(site_pfts, collapse = ", "))

# build trait.samples and ensemble.samples from param_sources mapping
# param_sources (from 021 metadata) is a named vector:
#   "grass.SLA" -> "grass", "mgmt.n_quantile" -> "management", "dummy" -> "dummy"
# we use this authoritative mapping instead of fragile string splitting

param_sources <- metadata$param_sources
if (is.null(param_sources)) {
  PEcAn.logger::logger.severe(
    "metadata$param_sources is NULL. Re-run 021 to regenerate metadata."
  )
}

# initialize per-PFT containers
trait.samples <- list()
for (pft_name in site_pfts) {
  trait.samples[[pft_name]] <- list()
}

for (col_name in names(param_sources)) {
  pft <- param_sources[[col_name]]

  # skip management and dummy; they don't go into sipnet.param
  if (pft %in% c("management", "dummy")) next

  # skip PFTs not assigned to any site
  if (!(pft %in% site_pfts)) {
    PEcAn.logger::logger.warn(
      "Param '", col_name, "' maps to PFT '", pft,
      "' which is not in any site. Skipping."
    )
    next
  }

  if (!(col_name %in% names(sobol_design))) {
    PEcAn.logger::logger.severe(
      "Column '", col_name, "' from metadata not found in design matrix"
    )
  }

  # use original_name (the bare SIPNET parameter name) as the column key
  original_name <- metadata$params[[col_name]]$original_name
  if (is.null(original_name)) {
    # fall back to stripping PFT prefix
    original_name <- sub(paste0("^", pft, "\\."), "", col_name)
  }

  trait.samples[[pft]][[original_name]] <- sobol_design[[col_name]]
}

# convert trait.samples (list of lists) to ensemble.samples (list of data.frames)
# PEcAn's run.write.configs() iterates over ensemble.samples[[pft]][row, ]
ensemble.samples <- purrr::map(trait.samples, \(param_list) {
  if (length(param_list) == 0) {
    return(tibble::tibble(.rows = nrow(sobol_design)))
  }
  tibble::as_tibble(param_list)
})

# verify row counts match
for (pft_name in names(ensemble.samples)) {
  nr <- nrow(ensemble.samples[[pft_name]])
  if (nr != nrow(sobol_design)) {
    PEcAn.logger::logger.severe(
      "Row count mismatch for PFT '", pft_name, "': ",
      nr, " vs ", nrow(sobol_design)
    )
  }
}

# build input_design (maps sample_id to IC/met ensemble indices)
input_design <- tibble::tibble(
  param       = sobol_design$sample_id,
  poolinitcond = sobol_design$ic_ensemble,
  met         = sobol_design$met_ensemble
)

# save samples.Rdata (format expected by run.write.configs)
sa.samples <- NULL
runs.samples <- list()
env.samples <- list()
pft.names <- names(trait.samples)
trait.names <- purrr::map(trait.samples, names)

save(
  ensemble.samples,
  trait.samples,
  sa.samples,
  runs.samples,
  pft.names,
  trait.names,
  env.samples,
  file = samples_outfile
)

PEcAn.logger::logger.info("Wrote ", samples_outfile)

# save input_design
cache_dir <- "cache"
if (!dir.exists(cache_dir)) dir.create(cache_dir, recursive = TRUE)

saveRDS(input_design, file.path(cache_dir, "input_design.rds"))
readr::write_csv(input_design, design_outfile)

PEcAn.logger::logger.info("Wrote ", design_outfile)