#!/usr/bin/env Rscript
# Generate per-sample management events from Sobol design matrix
#
# For each row in the Sobol design, maps quantile-based management
# parameters to crop-specific physical values per site, then builds
# PEcAn events JSON and converts to SIPNET events.in format via
# PEcAn.SIPNET::write.events.SIPNET()
#
# current scope: N fertilizer + compost
# other management events (tillage, planting, harvest, irrigation) pass
# through from the baseline calendar unchanged - they will be activated
# when the monitoring framework delivers the required remote sensing data products
#
# outputs: data/events/*.json, data/events/*.in, data/events/events_path_mapping.csv

library(readr, include.only = c("read_csv", "write_csv"))
library(yaml, include.only = "read_yaml")
library(jsonlite, include.only = c("read_json", "write_json"))
library(PEcAn.logger)

source("R/management_events.R")

# --- cli args ---
opts <- list(
  optparse::make_option(c("-c", "--config"),
    default = "000-config.yml",
    help = "Path to project config YAML [default: %default]"
  ),
  optparse::make_option(c("-d", "--design"),
    default = "data/sobol_design_matrix.csv",
    help = "Path to Sobol design matrix CSV [default: %default]"
  ),
  optparse::make_option(c("-o", "--output-dir"),
    default = "data/events",
    help = "Output directory for per-sample events [default: %default]"
  ),
  optparse::make_option(c("-f", "--force"),
    action = "store_true", default = FALSE,
    help = "Overwrite existing output"
  )
)

args <- optparse::parse_args(optparse::OptionParser(option_list = opts))

# --- config ---
cfg <- yaml::read_yaml(args$config)

output_dir <- args[["output-dir"]]
mapping_file <- file.path(output_dir, "events_path_mapping.csv")

# skip-if-exists guard
if (!args$force && file.exists(mapping_file)) {
  PEcAn.logger::logger.info(
    "Output exists: ", mapping_file, ". Use --force to regenerate. Skipping."
  )
  quit(save = "no", status = 0)
}

if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}

# --- load design matrix and metadata ---
design_path <- args$design
if (!file.exists(design_path)) {
  PEcAn.logger::logger.severe("Design matrix not found: ", design_path)
}

meta_path <- sub("\\.csv$", "_metadata.rds", design_path)
if (!file.exists(meta_path)) {
  PEcAn.logger::logger.severe("Design metadata not found: ", meta_path)
}

sobol_design <- readr::read_csv(design_path, show_col_types = FALSE)
metadata <- readRDS(meta_path)

PEcAn.logger::logger.info(
  "Loaded design: ", nrow(sobol_design), " samples x ", ncol(sobol_design), " cols"
)

# --- load site-crop mapping ---
# generated by 021_generate_sobol_design.R: per-site crop identity with
# min_n_g_m2 and max_n_g_m2 from PEcAn.data.land::look_up_ca_n_rate()
site_crop_path <- file.path(dirname(design_path), "site_crop_mapping.csv")
if (!file.exists(site_crop_path)) {
  PEcAn.logger::logger.severe("Site-crop mapping not found: ", site_crop_path)
}
site_crops <- readr::read_csv(site_crop_path, show_col_types = FALSE)

PEcAn.logger::logger.info(
  "Loaded site-crop mapping: ", nrow(site_crops), " sites, ",
  sum(site_crops$lookup_source == "crop_specific"), " crop-specific"
)

# load baseline events from canonical source (ccmmf/scenarios)
baseline_url <- cfg$events_baseline_url %||%
  "https://raw.githubusercontent.com/ccmmf/scenarios/main/data/events_baseline.json"

baseline_raw <- tryCatch(
  jsonlite::read_json(baseline_url),
  error = function(e) {
    PEcAn.logger::logger.severe("Cannot fetch baseline events: ", e$message)
  }
)
baseline_events <- if (!is.null(baseline_raw$events)) baseline_raw$events else baseline_raw

start_year <- as.integer(cfg$start_year %||% 2016L)
end_year <- as.integer(cfg$end_year %||% 2023L)
years <- seq(start_year, end_year)
site_id <- cfg$site_id

# --- identify mgmt columns in the design ---
mgmt_cols <- grep("^mgmt\\.", names(sobol_design), value = TRUE)
PEcAn.logger::logger.info(
  "Management columns: ", paste(mgmt_cols, collapse = ", ")
)

# --- management ranges from site-crop mapping ---
# compost C and C:N ranges come from PEcAn.data.land::look_up_ca_compost_amendment()
# via R/crop_lookup.R -> site_crop_mapping.csv
site_info_row <- site_crops[1, ]
compost_c_min_g_m2 <- site_info_row$compost_c_min_g_m2
compost_c_max_g_m2 <- site_info_row$compost_c_max_g_m2
compost_cn_min <- site_info_row$compost_cn_min
compost_cn_max <- site_info_row$compost_cn_max

PEcAn.logger::logger.info(
  "Compost: ", site_info_row$compost_material,
  " (C: ", round(compost_c_min_g_m2, 1), "-",
  round(compost_c_max_g_m2, 1), " g/m2",
  ", C:N: ", compost_cn_min, "-", compost_cn_max, ")"
)

# --- generate per-sample events ---
n_samples <- nrow(sobol_design)
events_in_paths <- character(n_samples)

for (i in seq_len(n_samples)) {
  n_quantile <- sobol_design[i, "mgmt.n_quantile", drop = TRUE]
  compost_quantile <- sobol_design[i, "mgmt.compost_quantile", drop = TRUE]
  cn_quantile <- sobol_design[i, "mgmt.cn_quantile", drop = TRUE]

  # map N quantile to crop-specific rate.
  # all sites share the same quantile, but each crop's [min, max] N range differs.
  # TODO extend to per-site mapping when MF delivers site-level data
  site_info <- site_crops[1, ]

  # inverse CDF of Uniform(min, max) -> value = min + q * (max - min)
  n_rate_g_m2 <- site_info$min_n_g_m2 +
    n_quantile * (site_info$max_n_g_m2 - site_info$min_n_g_m2)
  n_rate_kg_m2 <- PEcAn.utils::ud_convert(n_rate_g_m2, "g/m^2", "kg/m^2")

  # map compost quantile to material-specific C range (g/m2 -> kg/m2)
  org_c_g_m2 <- compost_c_min_g_m2 +
    compost_quantile * (compost_c_max_g_m2 - compost_c_min_g_m2)
  org_c_kg_m2 <- PEcAn.utils::ud_convert(org_c_g_m2, "g/m^2", "kg/m^2")

  # map C:N quantile to material-specific C:N range
  cn_ratio <- compost_cn_min + cn_quantile * (compost_cn_max - compost_cn_min)

  mgmt_row <- list(
    mgmt.nh4_n_kg_m2 = n_rate_kg_m2,
    mgmt.org_c_kg_m2 = org_c_kg_m2,
    mgmt.cn_ratio    = cn_ratio
  )

  # build PEcAn schema events JSON for this sample
  sample_events <- build_sample_events(
    mgmt_row        = mgmt_row,
    baseline_events = baseline_events,
    years           = years,
    site_id         = site_id,
    event_config    = cfg$event_config %||% list()
  )

  # write JSON (validated by PEcAn.data.land::validate_events_json)
  json_path <- file.path(output_dir, sprintf("events_sample_%d.json", i))
  jsonlite::write_json(
    list(sample_events),  # write.events.SIPNET expects array of site objects
    json_path,
    auto_unbox = TRUE,
    pretty = TRUE
  )

  # convert JSON -> SIPNET events.in via PEcAn.SIPNET::write.events.SIPNET
  # writes events-{site_id}.in in the output dir
  PEcAn.SIPNET::write.events.SIPNET(json_path, output_dir)

  # rename to per-sample filename
  sipnet_src <- file.path(output_dir, sprintf("events-%s.in", site_id))
  sipnet_dst <- file.path(output_dir, sprintf("events_sample_%d.in", i))
  file.rename(sipnet_src, sipnet_dst)

  events_in_paths[i] <- sipnet_dst

  if (i %% 500 == 0 || i == n_samples) {
    PEcAn.logger::logger.info(sprintf("  Generated %d / %d events files", i, n_samples))
  }
}

# --- write events path mapping ---
mapping <- tibble::tibble(
  sample_id      = sobol_design$sample_id,
  events_in_path = events_in_paths
)
readr::write_csv(mapping, mapping_file)

PEcAn.logger::logger.info(
  "Wrote ", n_samples, " events files and mapping to ", mapping_file
)

# TODO(multi-site management): when per-site management data is available,
#   generate per-site x per-sample events and register via setEnsemblePaths.
#   Currently ALL sites share the same management calendar.
